<?xml version="1.0" encoding="utf-8"?><testsuite errors="1" failures="0" name="pytest" skips="0" tests="1" time="29.397"><testcase classname="testcases.functional.heat.test_heat" file="testcases/functional/heat/test_heat.py" line="234" name="test_heat_template[WR_Neutron_ProviderNetRange.yaml]" time="23.613245010375977"></testcase><testcase classname="pytest" name="internal" time="0"><error message="internal error">Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/main.py&quot;, line 94, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/main.py&quot;, line 125, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 333, in &lt;lambda&gt;
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 596, in execute
    res = hook_impl.function(*args)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/main.py&quot;, line 150, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 333, in &lt;lambda&gt;
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 253, in _wrapped_call
    return call_outcome.get_result()
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 264, in __init__
    self.result = func()
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 596, in execute
    res = hook_impl.function(*args)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/runner.py&quot;, line 66, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/runner.py&quot;, line 78, in runtestprotocol
    nextitem=nextitem))
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/runner.py&quot;, line 122, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 333, in &lt;lambda&gt;
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/skipping.py&quot;, line 226, in pytest_runtest_makereport
    rep = outcome.get_result()
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 264, in __init__
    self.result = func()
  File &quot;/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py&quot;, line 596, in execute
    res = hook_impl.function(*args)
  File &quot;/home/ubuntu/cgcs/CGCSAuto/conftest.py&quot;, line 135, in pytest_runtest_makereport
    upload_res = collect_and_upload_results(test_name, res_in_tests, ProjVar.get_var(&apos;LOG_DIR&apos;), build=build_id)
  File &quot;/home/ubuntu/cgcs/CGCSAuto/utils/mongo_reporter/cgcs_mongo_reporter.py&quot;, line 44, in collect_and_upload_results
    lab_name = lab[&apos;short_name&apos;].upper()
TypeError: string indices must be integers</error></testcase></testsuite>